# Generated by Django 6.0.3 on 2026-04-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("strategy", models.CharField(max_length=200)),
                ("instrument", models.CharField(max_length=50)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "bar_type",
                    models.CharField(default="1-MINUTE-LAST-EXTERNAL", max_length=100),
                ),
                ("trade_size", models.FloatField(default=100000)),
                ("balance", models.FloatField(default=100000)),
                ("leverage", models.FloatField(default=50)),
                ("strategy_params", models.JSONField(blank=True, default=dict)),
                ("total_pnl", models.FloatField(default=0)),
                ("total_return_pct", models.FloatField(default=0)),
                ("num_trades", models.IntegerField(default=0)),
                ("win_rate", models.FloatField(default=0)),
                ("max_drawdown_pct", models.FloatField(default=0)),
                ("avg_trade_pnl", models.FloatField(default=0)),
                ("avg_win", models.FloatField(default=0)),
                ("avg_loss", models.FloatField(default=0)),
                ("profit_factor", models.FloatField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("balance", models.FloatField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_set",
                        to="dashboard.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument", models.CharField(max_length=50)),
                ("side", models.CharField(max_length=10)),
                ("quantity", models.FloatField()),
                ("open_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("realized_pnl", models.FloatField()),
                ("realized_return_pct", models.FloatField(default=0)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField()),
                ("duration_seconds", models.FloatField(default=0)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_set",
                        to="dashboard.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["opened_at"],
            },
        ),
    ]
