# Generated by Django 6.0.3 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='data_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='status',
            field=models.CharField(
                choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')],
                default='completed',
                max_length=20,
            ),
        ),
    ]
