# Generated by Django 6.0.3 on 2026-04-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_backtestrun_data_file_backtestrun_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestrun",
            name="extra_bar_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
