# Generated by Django 6.0.3 on 2026-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_backtestrun_extra_bar_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestrun",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="progress_pct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="total_bars",
            field=models.IntegerField(default=0),
        ),
    ]
