# Generated by Django 6.0.3 on 2026-04-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='running', max_length=20)),
                ('strategy', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=50)),
                ('bar_type', models.CharField(default='1-MINUTE-LAST-EXTERNAL', max_length=100)),
                ('started_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('account_currency', models.CharField(default='USD', max_length=10)),
                ('account_id', models.CharField(blank=True, default='', max_length=50)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('total_pnl', models.FloatField(blank=True, null=True)),
                ('total_return_pct', models.FloatField(blank=True, null=True)),
                ('num_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('max_drawdown_pct', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('avg_trade_pnl', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('realized_pnl', models.FloatField(blank=True, null=True)),
                ('realized_return_pct', models.FloatField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('fill_latency_ms', models.FloatField(blank=True, null=True)),
                ('slippage_ticks', models.FloatField(blank=True, null=True)),
                ('spread_at_entry', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='dashboard.papertradingsession')),
            ],
            options={
                'ordering': ['opened_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('equity', models.FloatField()),
                ('daily_pnl', models.FloatField()),
                ('open_positions', models.IntegerField()),
                ('drawdown_pct', models.FloatField()),
                ('utilization_pct', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='dashboard.papertradingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.papertradingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
