# Generated by Django 6.0.3 on 2026-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_papertradingsession_papertrade_risksnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertradingsession',
            name='instrument',
            field=models.CharField(max_length=200),
        ),
    ]
