# Generated by Django 6.0.3 on 2026-04-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_papertradingsession_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertradingsession',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papertradingsession',
            name='process_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
